# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stuff for Gadgeteers and Makers
subtitle: Gadgets, Software, Arduino and The Internet of Things
email: freakent@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I blog about the things that interest me, or things that if I don't write down
  I will probably forget. Professionaly I'm a tech guy with close to 30 years in the IT Industry.
  You could say I' a bit of a <i>Geek</i> who travels quite a lot. I write this Blog for
  myself, if it helps inform or entertain others then that's a bonus!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://freakent.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: freakent
github_username:  freakent

# Build settings
markdown: kramdown
#theme: minima
excerpt_separator: <!--more-->
paginate: 10
paginate_path: "/blog/page:num"
sass:
  style: compact # possible values: nested expanded compact compressed
# List of plugins in-use, supported by github pages
plugins:
#  - jekyll-include-cache
  - jekyll-feed
  - jekyll-paginate
#  - jekyll-seo-tag
collections_dir: content
#collections:
#  events:
#    output: true
#    permalink: /:title/index
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title:output_ext
      author: "Martin"
      media_path: /assets/img/ 

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts
  - archive
  - README.md
